# Let's explore!
In this notebook you can find an exploration of the data present in the 3W dataset.
To avoid formation of bias during model development, only the train split of our dataset will be used.

This exploration consists of graphs and metrics.
Some of the metrics (such as mean and std deviation) will be used later for data transformation.

### Preparing environment
By getting metadata table of the train split.

In [1]:
import sys

sys.path.append("..")  # Allows imports from sibling directories

from raw_data_manager import raw_data_inspector as rdi
from constants import config
from absl import logging
logging.set_verbosity(logging.DEBUG)

split_train_dir = "/home/ubuntu/lemi_3w/data/dataset_converted_v10101_split-20_source-all_class-all_well-all_train"
train_metadata = rdi.RawDataInspector(
    split_train_dir,
    config.DIR_PROJECT_CACHE / "train_metadata.parquet",
    True
)

train_metadata_table = train_metadata.get_metadata_table()
train_metadata_table

,class_type,source,well_id,path,timestamp,file_size,num_timesteps
hash_id,,,,,,,
74203bb,NORMAL,REAL,1.0,/home/ubuntu/lemi_3w/data/dataset_converted_v1...,2017-05-24 03:00:00,491415,17885
9fbd6f9,NORMAL,REAL,2.0,/home/ubuntu/lemi_3w/data/dataset_converted_v1...,2017-08-09 06:00:00,520154,17933
28804c5,NORMAL,REAL,6.0,/home/ubuntu/lemi_3w/data/dataset_converted_v1...,2017-05-08 09:00:31,349162,17970
fa71d94,NORMAL,REAL,6.0,/home/ubuntu/lemi_3w/data/dataset_converted_v1...,2017-08-23 19:00:00,279737,17949
07d061e,NORMAL,REAL,1.0,/home/ubuntu/lemi_3w/data/dataset_converted_v1...,2017-02-01 07:01:14,475846,17927
...,...,...,...,...,...,...,...
1def3c2,SEVERE_SLUGGING,REAL,14.0,/home/ubuntu/lemi_3w/data/dataset_converted_v1...,2017-09-20 11:00:53,977958,17948
ea66cf6,SEVERE_SLUGGING,SIMULATED,NaN,/home/ubuntu/lemi_3w/data/dataset_converted_v1...,NaT,2315903,61999
34f032a,SEVERE_SLUGGING,SIMULATED,NaN,/home/ubuntu/lemi_3w/data/dataset_converted_v1...,NaT,2259539,61999
deac7ec,SEVERE_SLUGGING,SIMULATED,NaN,/home/ubuntu/lemi_3w/data/dataset_converted_v1...,NaT,2045137,61999
c8867fa,SEVERE_SLUGGING,SIMULATED,NaN,/home/ubuntu/lemi_3w/data/dataset_converted_v1...,NaT,2359418,61999

In [2]:
from metric_acquisition import MetricAcquisition

metric_aquisition = MetricAcquisition(train_metadata_table)

cache_file_name = config.CACHE_NAME_TRAIN_MEAN_STD_DEV

metric_aquisition.get_mean_and_std_metric(
    cache_file_name, False
)

DONE:   0%|          | 0/1582 [00:00<?, ?it/s]

DEBUG:absl:Mean of means was adquired
             P-PDG         P-TPT       T-TPT     P-MON-CKP   T-JUS-CKP  \
0     0.000000e+00  1.420389e+07  116.794133  6.122810e+06   69.415705
1     0.000000e+00  8.715824e+06  117.581821  1.539264e+06   77.332955
2     4.203851e+07  1.806945e+07  118.569073  2.492268e+06   79.545939
3     4.485805e+07  2.114707e+07  116.569785  1.224582e+07   61.885166
4     0.000000e+00  1.001934e+07  119.033867  1.575567e+06   84.148449
...            ...           ...         ...           ...         ...
1577  2.424625e+07  1.511253e+07   44.579236  2.051035e+06   26.684643
1578  1.539201e+07  8.925425e+06  120.387588  4.042629e+06   94.437207
1579  2.077121e+07  1.138257e+07  119.183729  4.102729e+06   88.286792
1580  1.660494e+07  9.154420e+06  122.202564  4.044520e+06  101.257945
1581  1.898863e+07  1.076657e+07  116.316665  4.090173e+06   78.424427

        P-JUS-CKGL       QGL
0     3.052964e+06  0.000000
1     2.320418e+06  0.000000
2     6.233022e+06  0.000000
3     1.446720e+05  0.000000
4     1.569573e+06  0.000000
...            ...       ...
1577  1.865296e+07  1.154268
1578           NaN       NaN
1579           NaN       NaN
1580           NaN       NaN
1581           NaN       NaN

[1582 rows x 7 columns]
DEBUG:absl:Processed means was adquired
P-PDG         1.650749e+07
P-TPT         1.517584e+07
T-TPT         1.061237e+02
P-MON-CKP     4.729793e+06
T-JUS-CKP     7.843213e+01
P-JUS-CKGL    3.501117e+08
QGL           2.603752e-01
dtype: float64

DONE:   0%|          | 0/1582 [00:00<?, ?it/s]

DEBUG:absl:Mean of stds was adquired
             P-PDG         P-TPT      T-TPT     P-MON-CKP  T-JUS-CKP  \
0     1.650796e+07  9.727401e+05  10.670748  1.393445e+06   9.017328
1     1.650795e+07  6.460579e+06  11.462350  3.201251e+06   1.326954
2     2.698651e+07  2.893704e+06  12.445684  2.237588e+06   1.113869
3     2.835135e+07  5.971402e+06  10.446341  7.516233e+06  16.547521
4     1.650795e+07  5.156672e+06  12.910512  3.159368e+06   5.732314
...            ...           ...        ...           ...        ...
1577  7.747407e+06  1.085033e+06  62.752130  3.037988e+06  52.150639
1578  1.302697e+06  6.277145e+06  14.272520  6.875466e+05  16.129384
1579  4.467376e+06  4.035390e+06  13.093425  6.329557e+05  10.261665
1580  7.026096e+05  6.049567e+06  16.081285  6.855965e+05  22.862917
1581  2.709569e+06  4.559677e+06  10.288472  6.459461e+05   4.631962

        P-JUS-CKGL       QGL
0     3.470685e+08  0.260383
1     3.478010e+08  0.260382
2     3.438883e+08  0.260382
3     3.499768e+08  0.260382
4     3.485519e+08  0.260382
...            ...       ...
1577  3.314747e+08  1.064028
1578 -0.000000e+00 -0.000000
1579 -0.000000e+00 -0.000000
1580 -0.000000e+00 -0.000000
1581 -0.000000e+00 -0.000000

[1582 rows x 7 columns]
DEBUG:absl:Processed stds was adquired
P-PDG         1.201552e+07
P-TPT         3.687992e+06
T-TPT         1.629953e+01
P-MON-CKP     3.068575e+06
T-JUS-CKP     1.830099e+01
P-JUS-CKGL    2.450589e+08
QGL           1.638849e-01
dtype: float64

            mean_of_means  mean_of_stds
P-PDG        1.650749e+07  1.201552e+07
P-TPT        1.517584e+07  3.687992e+06
T-TPT        1.061237e+02  1.629953e+01
P-MON-CKP    4.729793e+06  3.068575e+06
T-JUS-CKP    7.843213e+01  1.830099e+01
P-JUS-CKGL   3.501117e+08  2.450589e+08
QGL          2.603752e-01  1.638849e-01